# Generated by Django 6.0 on 2025-12-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_codigo_sis_trigger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario__codigo_dc39f5_idx',
            old_name='inventario__codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario__serie_121e04_idx',
            old_name='inventario__serie_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario__etiquet_ae6cc4_idx',
            old_name='inventario__etiqueta_interna_idx',
        ),
    ]
