# Generated by Django 6.0 on 2025-12-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_inventario__codigo_idx_inventario__codigo_dc39f5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario_codigo_idx',
            old_name='inventario__codigo_dc39f5_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario_serie_idx',
            old_name='inventario__serie_121e04_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario_etiqueta_idx',
            old_name='inventario__etiquet_ae6cc4_idx',
        ),
    ]
