# Generated by Django 6.0 on 2025-12-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_inventario__codigo_dc39f5_idx_inventario_codigo_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('etiqueta_interna', models.CharField(blank=True, db_index=True, max_length=60)),
                ('condicion', models.CharField(blank=True, max_length=50)),
                ('grado', models.CharField(blank=True, max_length=10)),
                ('accesorios', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ArticuloFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inventario/articulos/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_venta', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sku',),
            },
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario__codigo_dc39f5_idx',
            old_name='inventario_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario__serie_121e04_idx',
            old_name='inventario_serie_idx',
        ),
        migrations.RenameIndex(
            model_name='inventarioitem',
            new_name='inventario__etiquet_ae6cc4_idx',
            old_name='inventario_etiqueta_idx',
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='inventarioitem',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='articulofoto',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.producto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='inventario__sku_814480_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['estado'], name='inventario__estado_f42789_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['serie'], name='inventario__serie_578989_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['etiqueta_interna'], name='inventario__etiquet_f2f09f_idx'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.UniqueConstraint(condition=models.Q(('serie', None), _negated=True), fields=('serie',), name='uniq_articulo_serie'),
        ),
    ]
