# Generated by Django 6.0 on 2025-12-28 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_articulo_articulofoto_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulo',
            name='uniq_articulo_serie',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('REPARACION', 'En reparación'), ('BAJA', 'Baja'), ('DESECHO', 'Desecho')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serie__isnull', True), _negated=True), models.Q(('serie', ''), _negated=True)), fields=('serie',), name='uniq_articulo_serie'),
        ),
    ]
