# Generated by Django 6.0 on 2025-12-27 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_articulo_articulofoto_producto_and_more'),
        ('ventas', '0002_folio_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['venta'], name='ventas_pago_venta_i_d7d1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo'], name='ventas_pago_metodo_d3c4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['folio'], name='ventas_vent_folio_f7143d_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='ventas_vent_estado_b0d674_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['creada_en'], name='ventas_vent_creada__4e8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['venta'], name='ventas_vent_venta_i_b7bd49_idx'),
        ),
        migrations.AddIndex(
            model_name='ventadetalle',
            index=models.Index(fields=['articulo'], name='ventas_vent_articul_b1f4ca_idx'),
        ),
    ]
